name: ipod_p27
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=2.7.15
  - bedtools=2.29.2
  - numpy=1.16.5
  - pandas
  - statsmodels
  - scipy=1.0.0
  - samtools=0.1.19
  - cutadapt
  - trimmomatic=0.32
  - matplotlib
  - toml
  - fastqc
  - tk
  - rpy2=2.8.6
